name: sheet
description: A fully customizable draggable bottom sheet.
version: 1.0.0
homepage: https://github.com/jamesblasco/modal_bottom_sheet

environment:
  sdk: '>=3.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  meta: any
   
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: any
  lints: any